# Generated by Django 4.2.2 on 2023-06-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('n_bedrooms', models.IntegerField(null=True)),
                ('n_bathrooms', models.IntegerField(null=True)),
                ('sqft', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
